name: Deploy to Cloud Run development environment
on:
    push:
        branches:
            - main
            - 'feature/**'
env:
    IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pawd-api/pawd-dev-api:latest
jobs:
    build-deploy-dev:
        name: Build and Deploy to dev
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn

            - name: Run tests
              run: yarn run test

            - name: Authenticate to Google Cloud
              uses: 'google-github-actions/auth@v2'
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_PAWD_DEV }}

            - name: Set up Cloud SDK
              uses: 'google-github-actions/setup-gcloud@v2'

            - name: Configure Docker Auth
              run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

            - name: Build and Push a Docker image
              run: |
                  docker build . --tag $IMAGE
                  docker push $IMAGE

            - name: Deploy the image
              run: |
                  GCP_SECRETS="\
                  ACCESS_TOKEN_EXPIRATION=ACCESS_TOKEN_EXPIRATION:latest,\
                  ACCESS_TOKEN_PRIVATE_KEY=ACCESS_TOKEN_PRIVATE_KEY:latest,\
                  ACCESS_TOKEN_PUBLIC_KEY=ACCESS_TOKEN_PUBLIC_KEY:latest,\
                  AUDIENCE=AUDIENCE:latest,\
                  CRYPTO_ALGORITHM=CRYPTO_ALGORITHM:latest,\
                  CRYPTO_IV=CRYPTO_IV:latest,\
                  CRYPTO_KEY=CRYPTO_KEY:latest,\
                  EMAIL_PASSWORD=EMAIL_PASSWORD:latest,\
                  ISSUER=ISSUER:latest,\
                  JWT_ALGORITHM=JWT_ALGORITHM:latest,\
                  MONGO_DATABASE_NAME=MONGO_DATABASE_NAME:latest,\
                  MONGO_PASSWORD=MONGO_PASSWORD:latest,\
                  MONGO_USERNAME=MONGO_USERNAME:latest,\
                  PAWD_EMAIL=PAWD_EMAIL:latest,\
                  REFRESH_TOKEN_EXPIRATION=REFRESH_TOKEN_EXPIRATION:latest,\
                  REFRESH_TOKEN_PRIVATE_KEY=REFRESH_TOKEN_PRIVATE_KEY:latest,\
                  REFRESH_TOKEN_PUBLIC_KEY=REFRESH_TOKEN_PUBLIC_KEY:latest,\
                  STRIPE_PUBLIC_KEY=STRIPE_PUBLIC_KEY:latest,\
                  STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest"

                  gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
                    --image $IMAGE \
                    --allow-unauthenticated \
                    --platform=managed \
                    --region=${{ secrets.GCP_REGION }} \
                    --min-instances=1 \
                    --service-account=${{ secrets.SA_NAME }} \
                    --set-secrets=$GCP_SECRETS
